### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by lubaso** [anthonyattard/Deedy-Resume-Cover-Letter#1]
I am using the template provided on Overleaf. I would like to change the `\namesection` font size and justify the paragraphs for the `\lettercontent`. Is there any way of doing that?

**Comment by anthonyattard** [comment]
Hi @lubaso, sorry for the delay.  So you would modify the `.cls` file under `\namesection`. 

`.cls` contains the styling and `.xtx` contains the structure. 

An example from [deedy-cover-letter.cls](https://github.com/anthonyattard/Deedy-Resume-Cover-Letter/blob/master/MacFonts/deedy-cover-letter.cls#L53)

```latex
\newcommand{\namesection}[3]{
    \centering{
        \sffamily
        \fontspec{Helvetica Neue UltraLight}\fontsize{40pt}{10cm}\selectfont #1 
        \fontspec{Helvetica Neue Light}\selectfont #2
    } \\
    \vspace{5pt}
    \centering{ \color{headings}\fontspec{Heiti TC Medium}\fontsize{11pt}{14pt}\selectfont #3}
    \noindent\makebox[\linewidth]{\rule{\paperwidth}{0.0pt}}
    \vspace{0pt}
}
\titlespacing{\section}{0pt}{0pt}{0pt}
```

Hope that helps!
